# Generated by Django 6.0 on 2025-12-31 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime'), ('book', 'Book'), ('manga', 'Manga')], max_length=20)),
                ('source', models.CharField(choices=[('tmdb', 'TMDb'), ('mal', 'MyAnimeList'), ('google_books', 'Google Books'), ('mangadex', 'MangaDex')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching / Reading'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan', 'Plan to Watch / Read')], default='plan', max_length=20)),
                ('current_season', models.PositiveIntegerField(default=0)),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media')},
            },
        ),
    ]
