# Generated by Django 6.0 on 2026-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='current_episode',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='current_season',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='rating',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime'), ('manga', 'Manga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(choices=[('tmdb', 'TMDb'), ('mal', 'MyAnimeList'), ('mangadex', 'MangaDex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching / Reading'), ('completed', 'Completed'), ('plan', 'Plan to Watch / Read')], default='plan', max_length=20),
        ),
    ]
