# Generated by Django 6.0 on 2026-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_usermedia_current_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='total_episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
